## Api
server.port=${SERVER_PORT}
## Security
api.security.jwt.secret=${JWT_SECRET_KEY:0745230@853426359!1102@824583197}
api.security.jwt.expiration=${JWT_EXPIRATION:86400000}
api.security.jwt.issuer=${JWT_ISSUER:bookstore-api}
## Spring datasource
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
## Hibernate Properties
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
## Spring Docs
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none
